service: calculator-service
runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
    URL_MULT: $URL_MULT
    URL_DIV: $URL_DIV
    URL_SUM: $URL_SUM
    URL_SUB: $URL_SUB