name: Build and deploy Dev Env
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploydev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v1
    - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
      env:
        URL_MULT: ${{ secrets.URL_MULT }}
        URL_DIV: ${{ secrets.URL_DIV }}
        URL_SUM: ${{ secrets.URL_SUM }}
        URL_SUB: ${{ secrets.URL_SUB }}
    - name: Deploy to Google App Engine
      uses: atRobertoFlores/gae_deploy_action@master
      with:
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
        project_name: ${{ secrets.PROJECT_NAME }}